### ISSUE TITLE
Github - pull correct branch names

### ISSUE THREAD

**Issue by jfmatth** [kubero-dev/kubero#105]
currently, the UI for GH repo's shows a static set of repos, it should show the correct ones.

For any repo, it shows the following branches:

```
dumm-pr2
dumm-pr
main
noProc
```

It will default to main

**Comment by mms-gianni** [comment]
wow ... this was a nasty bug. I did not finish my work here. All repositories except Gitea were affected. 

This is the fix and will be shipped in v1.8.3 UI image today. 

https://github.com/kubero-dev/kubero/commit/ad879ac09b74c15e9d9271781cb3867294ebfc89

**Comment by jfmatth** [comment]
Thanks.  Been sick for 1w,  but ill checkout when i can
