### ISSUE TITLE
Support JetbrainsSpace git repository

### ISSUE THREAD

**Issue by Split174** [kubero-dev/kubero#237]
We use the jetbraince space repository and would be very happy if kubero supported it.
https://www.jetbrains.com/help/space/repositories.html

**Comment by mms-gianni** [comment]
I'm not familiar with this service. 

But it has webhooks : 
- https://www.jetbrains.com/help/space/repository-webhooks.html 
- https://www.jetbrains.com/help/space/applications-api.html#create_webhook 

I'm currently searching for the "deployment keys" (or similar feature) 
Probably this one here : 
https://www.jetbrains.com/help/space/applications-api.html#add_ssh_key

**Comment by mms-gianni** [comment]
Another solution is to provide a user-generated deployment key during the connection process.
