### ISSUE TITLE
Behind reverse proxy 

### ISSUE THREAD

**Issue by grigoroffbenj** [kubero-dev/kubero#247]
Hi, 
I try to run kubero in debian 12 VM in our network. it will be behind a reverse proxy with wildcard *.dev.x.com. 
there is a guideline to deactivate SSL for all kubero ?
thanks in advance

**Comment by mms-gianni** [comment]
Hi
SSL is not checked (the switch) by default. This has to be switched on the app level. 

There is currently no feature planned to deactivate it in general (hide the switch)

**Comment by grigoroffbenj** [comment]
So if i forward *.mydomain to 443 the reverse proxy of kubero will pass to apps?
Thanks
