### ISSUE TITLE
Support of gRPC, WebSocket, and etc

### ISSUE THREAD

**Issue by nikitafedorov008** [kubero-dev/kubero#259]
**Does Kubero support a range of protocols like: gRPC, WebSocket?** 

Will an application deployed using a dockerfile using gRPC/WS/SSE or any other protocol other than HTTP work?

**Comment by mms-gianni** [comment]
Sure it does. Kubero creates standard Ingress resources on your Kubernetes cluster.

There is currently a limit with non HTTP-protocols (Like SSH) which require a special configuration on the ingress. But even this could be possible by deploying a custom Ingress Resource with kubectl.
