### ISSUE TITLE
Next.js support in Kubero Frameworks?

### ISSUE THREAD

**Issue by deadcoder0904** [kubero-dev/kubero#260]
I want a self-hosted PaaS that is reliable & doesn't give random errors.

I tried Coolify & Caprover but both give random errors for some reason.

My question is how easy it is to run a Next.js app on Kubero & how easy it will be to maintain it?

All I want is to set & forget. And maybe auto-deploy on git commits to github. Is it possible with Kubero?

**Comment by mms-gianni** [comment]
Kubero runs on Kubernetes. This might be a single VM or a cluster of VM's. This comes with some overhead, but standardizes a  lot of stuff and has many benefits ( Horizontal Autoscaling, restarting failed pods, ...). I'm currently running it on my 4GB Ram Raspbery Pi.

Kubero itself is Next.js app. And I'm running several selfbuild Node apps with Kubero. So this is my personal main usecase. 

Gitops (Deploying with a git push) is main feature of Kubero. There are currently 4 ways to deploy your app: 
1. Build with default images on startup in your init containers
2. Build with a Dockerfile 
3. Build with Flatpack (Comparable with Heroku's Buildpack)
4. Build an image on your CI/CD (Github Action e.g) and run it. 

Just do mention it: you can run any prebuilt image ( Like Grafana or Kuma ... )

**Comment by deadcoder0904** [comment]
Yeah, I tried installing but couldn't get past setup phase which is probably 2nd step.

It said something like `kind isn't installed` otherwise was giving it a shot.

Maybe, if you can make it easy clicks like Easypanel.io or Coolify.io, it'll be cool af.

Currently, wasn't able to go past 2nd step.

What's the minimum config bdw?

**Comment by mms-gianni** [comment]
yes, Kind and Kubectl are separate Binaries. You will need to install them separately. They will be handy anyway.

**Comment by deadcoder0904** [comment]
I went with https://easypanel.io which is probably the easiest self-hosted paas i've encountered so no need to try kubero for now.
