### ISSUE TITLE
How to add a new template?

### ISSUE THREAD

**Issue by montogeek** [kubero-dev/kubero#277]
I would like to contribute a Elixir or Phoenix Framework template to be supported by Kubero.

**Comment by montogeek** [comment]
After checking the docs, I need to create a Buildpack

**Comment by mms-gianni** [comment]
This is an example of a Framwork Template.

**Comment by mms-gianni** [comment]
This is an examp

**Comment by mms-gianni** [comment]
This is an example of a Framework template :
https://github.com/kubero-dev/kubero/blob/main/services/symfony/app.yaml 

To move them to the Framework index is actually a manual job I do on publish
https://github.com/kubero-dev/templates/blob/main/index-frameworks.json

There will be added a flag soon to mark templates as Framework-templates.

**Comment by montogeek** [comment]
Thanks!, Will dig into this this week :)

**Comment by mms-gianni** [comment]
There is now a template download button : 

![image](https://github.com/kubero-dev/kubero/assets/2052196/d854f1a6-8394-4bfe-8079-fa7017248207)
