### ISSUE TITLE
Waiting for Kubero UI is freeze forever

### ISSUE THREAD

**Issue by guzmanf** [kubero-dev/kubero#280]
hello community

when install Kubero UI, message Waiting for Kubero UI is freeze forever, force reboot and connect webUI but refuse connection
what is the problem ??

best regards

**Comment by mms-gianni** [comment]
The CLI is waiting for resources to become ready. The cause can vary. Maybe not enough resources on the worker nodes. Or permissions issues. 

Here are some troubleshooting commands you could try to find out what went wrong: 
https://docs.kubero.dev/Installation/troubleshooting#1-kubero-ui-is-not-accessible

**Comment by guzmanf** [comment]
thank @mms-gianni ...

Ii try with reinstall all from begining,

fresh install vps ubuntu 22.04 with apt & update

all command as execute like root

1) install docker      --> from https://docs.docker.com/engine/install/ubuntu/
2) install kind        --> [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
3) install kubero CLI  --> curl -L https://get.kubero.dev | bash
4) install kubectl     --> options Install using native package management -> Debian-based distributions
5) run kubero install with default options

and last line "Waiting for Kubero UI to be created" is freeze and not finish

in other terminal --> Troubleshooting Kubero installation

1. Kubero UI is not accessible

Check the Kubero UI CRD
kubectl get kuberoes.application.kubero.dev kubero -n kubero
result
------
NAME     AGE
kubero   18m

Check if the Kubero UI is running
kubectl get pods -n kubero
result
------
No resources found in kubero namespace.


Check the Kubero ingress
kubectl get ingress -n kubero
result
------
No resources found in kubero namespace.


Check if the DNS entry is correct
dig kubero.idscloud.online +noall +question +answer
result
------
;kubero.idscloud.online.                IN      A
kubero.idscloud.online. 1800    IN      A       190.114.255.98

but problem persist,

opinions...

best regard

**Comment by mms-gianni** [comment]
Interesting. I hope we can work that out. Never saw that. 

Do you see errors in the operator logs? 
```
kubectl logs -n kubero-operator-system kubero-operator-controller-manager-XXXXX
```

**Comment by guzmanf** [comment]
@mms-gianni 

kubectl get pods --all-namespaces | grep kubero-operator-controller-manager
result
------
kubero-operator-system   kubero-operator-controller-manager-d5cbcc6dd-55gw2   0/2     Pending     0          112m

kubectl logs -n kubero-operator-system kubero-operator-controller-manager-d5cbcc6dd-55gw2
no result, command return nothing

**Comment by mms-gianni** [comment]
So the Operator is not running. That's what causes the problems. 

This should look something like this: 
```
NAME                                                  READY   STATUS    RESTARTS        AGE
kubero-operator-controller-manager-64b47f59d8-9wddk   2/2     Running   1  (3d3h ago)   17d 
```

You might find the reason in the events. But they are kept by back by kubernetes only for 1 hour. So they might be gone already in your case. 

Just delete this pod. It should come up within some seconds. You should then see fresh events. 

```
get events                                                                                                                                                                main * ] 10:14 pm
LAST SEEN   TYPE     REASON             OBJECT                                                    MESSAGE
43s         Normal   Killing            pod/kubero-operator-controller-manager-d5cbcc6dd-bqchb    Stopping container manager
43s         Normal   Killing            pod/kubero-operator-controller-manager-d5cbcc6dd-bqchb    Stopping container kube-rbac-proxy
43s         Normal   Scheduled          pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Successfully assigned kubero-operator-system/kubero-operator-controller-manager-d5cbcc6dd-shj7h to kubero-v2-1-control-plane
42s         Normal   Pulled             pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0" already present on machine
42s         Normal   Created            pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Created container kube-rbac-proxy
42s         Normal   Started            pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Started container kube-rbac-proxy
42s         Normal   Pulled             pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Container image "ghcr.io/kubero-dev/kubero-operator/kuberoapp:v0.0.155" already present on machine
42s         Normal   Created            pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Created container manager
42s         Normal   Started            pod/kubero-operator-controller-manager-d5cbcc6dd-shj7h    Started container manager
43s         Normal   SuccessfulCreate   replicaset/kubero-operator-controller-manager-d5cbcc6dd   Created pod: kubero-operator-controller-manager-d5cbcc6dd-shj7h
24s         Normal   LeaderElection     configmap/kubero-operator                                 kubero-operator-controller-manager-d5cbcc6dd-shj7h_d877f3ad-24bb-4f8e-824e-501ab2933ca4 became leader
24s         Normal   LeaderElection     lease/kubero-operator                                     kubero-operator-controller-manager-d5cbcc6dd-shj7h_d877f3ad-24bb-4f8e-824e-501ab2933ca4 became leader
```

**Comment by mms-gianni** [comment]
Happy I was able to help. 

BTW: I got a small dev Kubernetes running on a single RaspberryPi with 4GB RAM. I used k3s to install it. 

![raspberyPi](https://github.com/kubero-dev/kubero/assets/2052196/3e5d6008-a754-4f0f-bc1c-822e14941bf3)
