### ISSUE TITLE
EKS integration

### ISSUE THREAD

**Issue by siteshplivo** [kubero-dev/kubero#297]
Can we run kubero on Amazon EKS?  If not, what kind of integrations we would need to deploy on kubero on EKS

**Comment by mms-gianni** [comment]
@xorl made some changes to tackle Permission issues with ServiceAccounts. But I couldn't review it yet since I'm a bit occupied by other projects. 


https://github.com/kubero-dev/kubero/pull/292

**Comment by xorl** [comment]
It does work, just use “kind” as the deployment method and when it asks which kind of authentication use aws. On route53, any domains used, just CName *.domain.tld to the ELB created by the ingress. There were some other things I forgot.
