### ISSUE TITLE
How can I add another Kubernetes cluster context?

### ISSUE THREAD

**Issue by krzwiatrzyk** [kubero-dev/kubero#298]
There is a field in creating new pipeline to select Kubernetes cluster context but I cannot find any information how can I add one to Kubero

**Comment by krzwiatrzyk** [comment]
Also, full example link for configuration file from the docs doesn't point to valid file: https://github.com/kubero-dev/kubero/blob/main/config.yaml

**Comment by mms-gianni** [comment]
Kubero usually runs in the with the InCluster Context which does not require a kubeconfig. 

To use Kubero with multiple clusters use the KUBECONFIG_BASE64 Variable in the the kubero-secret https://docs.kubero.dev/installation/ 

This is a standard kubeconfig file: https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/ 

Remember that this variable is encoded twice with base64 when stored in the secret.

**Comment by krzwiatrzyk** [comment]
Copy that, thanks! I will test that out and maybe propose a PR for docs to describe that better
