### ISSUE TITLE
Not being able to open networking

### ISSUE THREAD

**Issue by cskiwi** [kubero-dev/kubero#299]
hi,

I've noticed that when you create an app and enable "Advanced App Configuration" the new expansion panels don't open except the security.

If you would open the networking, it would open security as well.

I tried fixing it, but my vue knowledge is to limited for this, and from the vueify playground it should have worked [playground](https://play.vuetifyjs.com/#eNrtVE2P0zAQ/StDLm2lNmVZuFRtpRUXkLgiDpSDsSdlhD+y9jh0tep/Z+w0ogsrceJGLrFnJu+9eWPn82OTol7f9X07ZGw2zZbR9VYx7g8eYDus0g9i/a1sAIaVCwbt7tAoMyiv0RyaMWPV1xq/u8RBEOFt8B0dc1RMwU+VOtgQpbKP5FR8mMLkE3JZ7rfriVQkVBGGhqqm6sFTr3wSwJW80SYYVCTluYjSOkRTuS71z30xZUo7XZVCwg63k5LybL7jQ0lcxxhPheRDiOiA+pQdmNILJGJQDnkpvUkXmpFzBGWop6TJHwEtSTKJKyYAUk7iosC5Xj4mr8mQyZ4hc7FR4AF5hEZw6ugVKEv3WbXwkQE9OcEGR2UxyFa5JdxnSuBD4pgN4AmjJq6uQ7ZWOR1G5FJEiQpThaReigGVCHeiKYwNCBW3TzontiitvxfNv+J1UL95e5nY342n7plD9H8m/2gmdR5/ZtJ4x9fj/dqur66+bJOO1LNYxLmvhVTMYXiEiB2coYvBwUz+GrNx6EUng0tH2JWK+ewdWhvgU4jWvJgtCsEIeQ1fgUVWATbYqWyFYBRsFKsNzBew28P8EgOxeTwzG+iUTbgc4+dFXZyfkDTnZXPbvm5f3TRl8aa9edl8+QnejqSW)

**Comment by mms-gianni** [comment]
Interesting. Still investigating. Can't see now how and when I've broken that.

**Comment by mms-gianni** [comment]
That was a tricky one. I assume this is some strange behavior from vuetify where the wring ID is pushed to the v-model, when new pannels are added.

**Comment by mms-gianni** [comment]
Shipping fix with v2.0.3
