### ISSUE TITLE
Something broke with the latest operator (v0.0.159)

### ISSUE THREAD

**Issue by cskiwi** [kubero-dev/kubero#312]
Hi,

When I updated to the latest operator via:
`kubectl apply -f https://raw.githubusercontent.com/kubero-dev/kubero-operator/main/deploy/operator.yaml`
I've encountered the error with my nodejs app that the package.json file coulndn't be found.

I didn't have time to save the exact logs.  hopefully I'll find some time later this week. but wanted to report this already.

Current workaround = reverting to last version:
`kubectl apply -f https://raw.githubusercontent.com/kubero-dev/kubero-operator/d530ff5238d6ed80daf798f0a2817088c4c8b9f4/deploy/operator.yaml`

**Comment by mms-gianni** [comment]
That's strange. It has very few changes between these versions: 

https://github.com/kubero-dev/kubero-operator/commit/1be5a8ea51b8f60a61a6b452efd5d889b6f02973 

I can't imagine the operator affecting the fetched code. I suspect a permission problem or a failed fetch ... 

Those permissions might be changed by saving the settings in latest version (filling missing permission fields with defaults)

**Comment by mms-gianni** [comment]
Great to hear. Thanks for the feedback.
