### ISSUE TITLE
Having multiple projects connected triggers all of them when one repo get's updated

### ISSUE THREAD

**Issue by cskiwi** [kubero-dev/kubero#321]
hi,

I just noticed that when I update one of my github connected projects that another GH connected one also re-deploys.
I wouldn't think that this is normal behaviour? 

Do I need to configure something specific to prevent this? or is this normal?

**Comment by mms-gianni** [comment]
Found the bug. I assume it happens only when branches have the same name across multiple repositories. This usually the case with master and main, but my also apply on any other overlapping name. 

I was not specific enough when searching for the affected apps.
