### ISSUE TITLE
Running Kubero on microk8s

### ISSUE THREAD

**Issue by mms-gianni** [kubero-dev/kubero#330]
Hey there. I was wondering if anyone is running Kubero on a microk8s.

Do you had any issues or needed to change something?

**Comment by Aju100** [comment]
Hi @mms-gianni ,

I am testing on kind cluster. Looks like it got stuck over creating the UI dashboard of kubero. Do we have any way to trace out the causes ?


<img width="1616" alt="Screenshot 2024-04-20 at 8 54 14 AM" src="https://github.com/kubero-dev/kubero/assets/29862610/88097d24-b99e-4ad9-921d-96386e7cf913">

**Comment by ajutamangdev** [comment]
Hi @mms-gianni 

I am testing on kind cluster. Looks like it got stuck over creating the UI dashboard of kubero. Do we have any way to trace out the causes ?

<img width="1497" alt="Screenshot 2024-04-20 at 9 26 21 AM" src="https://github.com/kubero-dev/kubero/assets/167596183/b223da3c-0311-422f-9561-1dfc619391d5">

**Comment by mms-gianni** [comment]
Did you try it without OLM?

OLM is a bit out of date.

**Comment by ajutamangdev** [comment]
No I haven't tried without OLM. Let me clean up the cluster resources on kind and perform without OLM. Will get back to you with some feedbacks. cc @mms-gianni

**Comment by mms-gianni** [comment]
I've tested it now with OLM on kind cluster. 

Everything worked as expected. Only the cert-manager cluster issuer is not installed by the kubero-cli when OLM is selected. 

Fixed it in kubero-cli v2.2.0 https://github.com/kubero-dev/kubero-cli/pull/35/files

**Comment by ajutamangdev** [comment]
Great @mms-gianni . I also installed microk8s cluster on my machine. Looks like we don't have options via kubero to install.
![Screenshot from 2024-04-21 13-42-51](https://github.com/kubero-dev/kubero/assets/167596183/ca5a72ca-f4b9-42b4-ae45-07b8d84b4dc5)

Are any other ways on how we can install kubero at microk8s ? I also go through documentation instructions.
I was able to install kubero-operator. 
![i](https://github.com/kubero-dev/kubero/assets/167596183/bb36f04e-e05e-4ce6-a882-88ab8c143707)

Just my suggestion here, how about it installs in the default current context cluster with default configuration ?

**Comment by ajutamangdev** [comment]
For the microk8s, I was able to install but improvements of documentation should be done.

**Comment by mms-gianni** [comment]
@ajutamangdev 

I've created a dedicated installation instructions page for microk8s (k3s, colima, minikube are following)

What do you think 🤔 did I missed something?

https://docs.kubero.dev/installation/installation-microk8s/

**Comment by ajutamangdev** [comment]
@mms-gianni Looks good to me but this one needs to get improve. Before sharing ```k```, you can share this instruction ti define ```alias k=kubectl```. 

```
k get nodes -o wide
```
