### ISSUE TITLE
Add Issue & PR templates

### ISSUE THREAD

**Issue by ajutamangdev** [kubero-dev/kubero#338]
Having default templates while raising issue or PR will help any incoming or existed contributor to specify their requirements.  This will let us to know more context what they are asking for.

We can have these following templates
- bug report
- feature request
- PR template
- enhancement
- other

Here are some samples
- https://github.com/loft-sh/devpod/blob/main/.github/ISSUE_TEMPLATE
- https://github.com/envless/envless/tree/main/.github/ISSUE_TEMPLATE

We can apply this templates across every active repositories of kubero. 

cc @mms-gianni

**Comment by mms-gianni** [comment]
This was somewhere on my dependency list. Good idea. 

I've disabled issues on all other repositories in favor of having them in this repository. There are not many issues, but it's hard for me to monitor them all.

**Comment by mms-gianni** [comment]
I'd rather use the yaml version:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms 

there is even a project to create them : 
https://github.com/kerhub/issue-forms-creator?tab=readme-ov-file

**Comment by ajutamangdev** [comment]
No worries, meanwhile we can have these templates as a yaml format at kubero. We can have rest once the project get more attention and potential contributor. @mms-gianni

**Comment by ajutamangdev** [comment]
I will check over above issue form creator. 😀
