### ISSUE TITLE
[FEATURE]: Add Buildpacks.io builder

### ISSUE THREAD

**Issue by hany** [kubero-dev/kubero#344]
### Description

I understand that the use of the term "buildpacks" used by Kubero is not the same as the concepts [Cloud Native Buildpacks.io (CNB)](https://buildpacks.io/) brings. We've been using CNB's for some time, and appreciate its simplicity and auto-detection capabilities. It's quite flexible and configurable (for example, being able to specify versions of the languages used, or having it auto-detect the version based on standard files from the repo). For example, here are the various supported package management capabilities for Python-based apps:

https://paketo.io/docs/howto/python/#use-a-package-manager

Or auto-detection of Ruby versions:

https://paketo.io/docs/howto/ruby/#override-the-detected-ruby-version

Has there been any thoughts for adding or utilizing Buildpacks.io or [Paketo](https://paketo.io)? It may alleviate the need to maintain a repo for the various "buildpacks" and utilize a common framework.

### Possible solution

Utilizing Buildpacks.io or Paketo.io for buildpacks instead of maintaining a [Kubero Buildpacks Repo](https://github.com/kubero-dev/buildpacks).

**Comment by mms-gianni** [comment]
Actually, I'm working on that one using https://github.com/buildpacks-community/kpack as an option. 

The Kubero "buildpack" naming is misleading. This will be the first thing to change.

**Comment by hany** [comment]
> Actually, I'm working on that one using https://github.com/buildpacks-community/kpack as an option.
> 
> The Kubero "buildpack" naming is misleading. This will be the first thing to change.

That's great! Is there a place where we can follow your progress on this one?

**Comment by mms-gianni** [comment]
@hany I've just started to work on this topic for version 2.4.0 

I did manage to build and push an image with kpacks. However, there is still an issue on how to handle the finished build. There for I plan to create a separate job to handle that. This is managed in a separate image and repository. 

https://github.com/kubero-dev/deployer

**Comment by mms-gianni** [comment]
Kubero will get a whole new CRD (api) to handle builds. This has a lot of benefits. It will be possible to store build logs, list all builds, and reset to an older build. 

Kubero Runbuilds won't be affected and keep working as usual. But I tend to focus kubero on image building. 

Next step was to cleanup the registry configuration and prepare it for kpacks
https://github.com/kubero-dev/kubero-operator/commit/69ab305d54d35a201d00c9ae72fd45e2a52b5d9d

**Comment by mms-gianni** [comment]
closed by accident with the merge

**Comment by mms-gianni** [comment]
Quite a time since my last update. 


Still working almost daily on this topic. 

Here is my latestes WIP

![image](https://github.com/kubero-dev/kubero/assets/2052196/e167eebd-5128-49a0-94bb-2064e72d545c)

**Comment by mms-gianni** [comment]
Making some more progress... added state, activity and duration
![image](https://github.com/user-attachments/assets/aee8dae7-edce-4b44-9403-cba8523e432c)

**Comment by mms-gianni** [comment]
So ... final progress made today. Refactored all the kpack stuff for native buildpack support. 

![image](https://github.com/user-attachments/assets/0d984582-f55f-4691-926c-0c12f75bca7c)

**Comment by mms-gianni** [comment]
Finally done
