### ISSUE TITLE
Branches for apps always use main

### ISSUE THREAD

**Issue by james-martinez** [kubero-dev/kubero#37]
Currently when setting up different branches for each environment they always use main.

**Comment by mms-gianni** [comment]
thank you for opening an Issue. I will look into it asap.

**Comment by james-martinez** [comment]
Great. I hope to collaborate with you in the future!

**Comment by mms-gianni** [comment]
Sure. I'd love to! Let me know if I can assist you with anything. I've set up discord, slack and github Discussion Board. They are still very empty. 

I found two Bugs, causing this behavior: 

1) This caused a malformed branch name: 
https://github.com/kubero-dev/kubero/commit/3aea5a8637a5a9cfed444844748c9b1dbcb96b77 
Will bis shipped with the next tag v1.3.3

2) But the main cause is a bit embarrassing for me. I forgot to uncomment the git checkout
https://github.com/kubero-dev/buildpacks/commit/3acc92af9793254c083cfb18b5664e728d945091
