### ISSUE TITLE
Karpenter or Cluster Autoscaler Setup docs

### ISSUE THREAD

**Issue by manjeshpv** [kubero-dev/kubero#375]
### Description

I want to keep the infra elastic, also want to use kubero

If anyone in kubero community using karpenter or cluster autoscaler

please share step by step docs 

### Possible solution

https://github.com/aws/karpenter-provider-aws

**Comment by mms-gianni** [comment]
I had finally a closer look into it. I don't think this should be in the scope of kubero since it would increas the complexitiy by a lot. Code wise, but also in the UI.
