### ISSUE TITLE
Document which permissions are needed for git providers

### ISSUE THREAD

**Issue by james-martinez** [kubero-dev/kubero#38]
can we get a table or list of minimum required permissions when generating tokens for each git provider

**Comment by mms-gianni** [comment]
This is a good idea. 

I'm generally a bit unhappy with the current documentation and am looking for a better solution. 

This is actually what I have configured for my Github Personal Access Token. 
![image](https://user-images.githubusercontent.com/2052196/207603790-9734bd01-3490-48ed-8f7c-8b7e9592a162.png)

**Comment by james-martinez** [comment]
Excellent!

**Comment by james-martinez** [comment]
Or maybe have the ui ask for  permissions

**Comment by mms-gianni** [comment]
My plan, for now, is to move the docs from the wiki to the public main repository, so they can be edited by everyone. This may take some time.

**Comment by james-martinez** [comment]
Great thanks 👍🏼
