### ISSUE TITLE
Liveness and Readiness probes

### ISSUE THREAD

**Issue by james-martinez** [kubero-dev/kubero#39]
Currently I am setting up a nodejs app and not listening on any ports. My deployments don't go into a ready state and restart because the liveness and readiness timeouts. Can liveness and readiness probes be configured or turned off ?

**Comment by mms-gianni** [comment]
I see your Problem. I think the liveness probe is required for a non-disruptive deployment. Kuberntes will only terminate the running pod, after a successful health check.
 
So the best way should be to make it work. 

This is how the "liveness" is defined : 
https://github.com/kubero-dev/kubero-operator/blob/main/helm-charts/kuberoapp/templates/deployment-worker.yaml#L106-L113

This is a problem for apps not answering on the root path "/" or GET method. The port is configurable and referenced as "http"  

So in your case, an app without a HTTP-Endpoint at all, it would be best, to run it as "worker" pod and disable the "web" pods. 

And "worker"-deployments should not check any health at all. ( which may cause disruptive deployments, but this should be tolerable in worker apps)  

I will remove this section in the worker deployment with the next operator release.

**Comment by james-martinez** [comment]
Thanks for your help. I did try on a worker and you are correct the http probes still exist. Since they are workers can there be a switch to disable ingress in the ui?

**Comment by mms-gianni** [comment]
I will disable it for worker-pods in next operator release.

**Comment by james-martinez** [comment]
Keep in mind probes can be configured as commands too 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

**Comment by mms-gianni** [comment]
Interesting. Never came across that. But for simplicity, I think it is ok to start without a health check on workers.

**Comment by james-martinez** [comment]
I agree thanks for your support!

**Comment by mms-gianni** [comment]
Kubero operator 0.0.75 has been released, with the removed health check on workers.
