### ISSUE TITLE
Finishing `kubero install` results in a 404 blank page on WebUI

### ISSUE THREAD

**Issue by WK-Haneeth** [kubero-dev/kubero#436]
### Describe the bug

Installed kubectl and kind on a fresh VM, and followed the "Quickstart" guide from docs.kubero.dev, installed the binary through the installation script.

Followed the defaults from `kubero install` and passed my github token when asked for, the installation successfully finished but when I try to access the WebUI it results in an nginx 404.

Any help is appreciated, thank you for your timeQ

### Steps to reproduce

1. Set Up a fresh Ubuntu 24.04 LTS VM, with `kubectl` & `kind` to set kubero on a local machine
2. Fetch the Kubero binary through `curl -fsSL get.kubero.dev | bash`
3. Run `kubero install` and verify that both the prerequisites are present and detected.
4. Go through the step-by-step instructions and provide the installer the necessary info (I didn't need Prometheus and SSL for the WebUI since it's just for testing, those were the only two options where I deviated from the defaults)
5. Wait for it to finish and give me the all clear
6. Try opening up the server with the default port of 80 and get greeted with an nginx 404

### Expected behavior

A Login page upon connection

### Screenshots

![image](https://github.com/user-attachments/assets/0fe7484b-d965-4108-a168-6ba5d3ee4218)
![image](https://github.com/user-attachments/assets/c38ea430-ceb2-430d-992c-eca766696488)

### Debug information

```
admin@kubero-vm:~$ kubero debug
No config file found; using defaults
Error while loading credentialsConfig file: Config File "credentials" Not Found in "[/etc/kubero /home/cpadmin/.kubero]"
Kubero CLI
kuberoCLIVersion: v2.4.0
OS: linux
Arch: amd64
goVersion: go1.21.13

Kubernetes
clientVersion:
  buildDate: "2024-09-27T04:29:24Z"
  compiler: gc
  gitCommit: 633f2e97262a75125dd093765c5faf620b5223fe
  gitTreeState: clean
  gitVersion: v1.30.5-dispatcher
  goVersion: go1.22.6
  major: "1"
  minor: 30+
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3


Kubero Operator

Kubero Operator Image


Kubero UI

Kubero UI Ingress

Kubero UI Secrets

Kubero UI Image


Cert Manager

Cert Manager Cluster Issuers
```

**Comment by mms-gianni** [comment]
Did you try http://kubero.localhost:80 ? 404 is at least an Nginx answer. 

The debug looks very empty tough.

**Comment by WK-Haneeth** [comment]
> Did you try http://kubero.localhost:80 ? 404 is at least an Nginx answer.
> 
> The debug looks very empty tough.
> 
> In case you are not running on a local host, point the DNS to the clusters public ip, and change the ingresss to this Domain.

Thank you for the quick reply,
I am not running on localhost, it's a VM that I had set-up on a Proxmox Node and I just sshed into it. I just wanted to quickly try Kubero myself because the demo you had for it was read-only.
Can I ask what you meant by changing the ingress to the domain?

**Comment by mms-gianni** [comment]
Ingress works kind like an Apache Vhost. 

So you will need a Domain pointing to your 172.16.xx.xx ip so the ingress can match the app. The ingress is configured in Kubero's CRD.

'''
kubectl -n kubero kuberoes kubero
''' 

Find kubero.localhost and change it to your domain. 

'''
*.mydomain.com A 600 172.16.xx.xx
'''

The wildcard comes handy when provisioning you apps. 

/Written in my mobile phone 😬
