### ISSUE TITLE
Web pods always is set to 1 in UI

### ISSUE THREAD

**Issue by james-martinez** [kubero-dev/kubero#48]
When setting up an app in the UI, I turn web pods to 0 and worker pods to 1 but web pods still return 1 when the app generates the Kuberoapp .
<img width="315" alt="Screenshot 2022-12-19 at 9 35 03 AM" src="https://user-images.githubusercontent.com/1388493/208462777-47199628-90be-4b44-8521-2a440e385ec9.png">
<img width="393" alt="Screenshot 2022-12-19 at 9 41 10 AM" src="https://user-images.githubusercontent.com/1388493/208463830-d22b5dd2-1edb-40e9-bb11-2e55a1dcc7c7.png">

**Comment by mms-gianni** [comment]
I will try to reproduce that.

**Comment by mms-gianni** [comment]
And here is the bug : 
https://github.com/kubero-dev/kubero/blob/main/client/src/components/apps/new.vue#L799 

0 is handled as false and transformed to 1 

I will fix this in v1.4.2

**Comment by james-martinez** [comment]
#58
