### ISSUE TITLE
New apps initialize with 1 webpod

### ISSUE THREAD

**Issue by james-martinez** [kubero-dev/kubero#62]
Upon a new app creation

<img width="240" alt="Screenshot 2022-12-22 at 2 50 16 PM" src="https://user-images.githubusercontent.com/1388493/209223988-78a23ad1-fd2b-4331-afb6-899af667dc38.png">

Web requests still POST to https://kubero.local.domain/api/apps

<img width="846" alt="Screenshot 2022-12-22 at 2 52 12 PM" src="https://user-images.githubusercontent.com/1388493/209224234-8c1fb95a-9430-4125-b8ba-79b5bae41dea.png">

Making an PUT request on the frontend to https://kubero.local.domain/api/pipelines/pipeline1/production/abc works correctly

Relates to #48

**Comment by mms-gianni** [comment]
This might be a caching issue. I could not replicate it in my local dev environment. 

I'll investigate it further in my cloud now.

**Comment by mms-gianni** [comment]
Ah ... got it now, after reviewing your PR. At least I made it consistently wrong 😄 

Thank you.
