### ISSUE TITLE
Website header is hidden on Firefox/Brave

### ISSUE THREAD

**Issue by impressivewebs** [kubero-dev/kubero#90]
Is the header for the website supposed to look like this?

https://i.imgur.com/VmHMieM.png

Same result in Firefox and Brave (so I assume Chrome is the same). This seems to be happening only on wide views, about 992px and up.

**Comment by mms-gianni** [comment]
Thank you for providing this screenshot. It looks awful.

**Comment by mms-gianni** [comment]
Fixed now with this commit : 
https://github.com/kubero-dev/website/commit/7c726f1be31ceb3fc6cc315c35ed7d049d6d931e
